packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
catalog:
  "@eslint/eslintrc": ^3.2.0
  "@payloadcms/db-postgres": 3.55.0
  "@payloadcms/next": 3.55.0
  "@payloadcms/payload-cloud": 3.55.0
  "@payloadcms/richtext-lexical": 3.55.0
  "@payloadcms/ui": 3.55.0
  "@playwright/test": 1.54.1
  "@react-router/dev": ^7.7.1
  "@react-router/node": ^7.7.1
  "@react-router/serve": ^7.7.1
  "@tailwindcss/vite": ^4.1.4
  "@testing-library/react": 16.3.0
  "@types/cors": ^2.8.17
  "@types/express": ^4.17.21
  "@types/node": ^22.5.4
  "@types/react": 19.1.8
  "@types/react-dom": 19.1.6
  "@vitejs/plugin-react": 4.5.2
  cors: ^2.8.5
  cross-env: ^7.0.3
  dotenv: ^16.3.1
  eslint: ^9.16.0
  eslint-config-next: 15.4.7
  express: ^4.18.2
  graphql: ^16.8.1
  isbot: ^5.1.27
  jsdom: 26.1.0
  next: 15.4.7
  payload: 3.55.0
  playwright: 1.54.1
  playwright-core: 1.54.1
  prettier: ^3.4.2
  react: 19.1.0
  react-dom: 19.1.0
  react-router: ^7.7.1
  sharp: 0.34.2
  tailwindcss: ^4.1.4
  typescript: 5.7.3
  vite: ^6.3.3
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.3
