packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/eslintrc': ^3.2.0
  '@payloadcms/db-postgres': 3.55.0
  '@payloadcms/next': 3.55.0
  '@payloadcms/payload-cloud': 3.55.0
  '@payloadcms/richtext-lexical': 3.55.0
  '@payloadcms/ui': 3.55.0
  '@playwright/test': 1.54.1
  '@react-router/dev': ^7.7.1
  '@react-router/express': ^7.7.1
  '@react-router/node': ^7.7.1
  '@tailwindcss/vite': ^4.1.4
  '@testing-library/react': 16.3.0
  '@testing-library/jest-dom': ^6.4.2
  '@testing-library/user-event': ^14.5.2
  '@vitest/ui': 3.2.3
  '@types/compression': ^1.7.5
  '@types/cors': ^2.8.17
  '@types/express': ^4.17.21
  '@types/express-serve-static-core': ^4.19.5
  '@types/morgan': ^1.9.9
  '@types/node': ^22.5.4
  '@types/react': 19.1.8
  '@types/react-dom': 19.1.6
  '@vitejs/plugin-react': 4.5.2
  compression: ^1.7.5
  cross-env: ^7.0.3
  dotenv: ^16.3.1
  eslint: ^9.16.0
  eslint-config-next: 15.4.7
  express: ^4.18.2
  graphql: ^16.8.1
  isbot: ^5.1.27
  jsdom: 26.1.0
  lefthook: ^1.8.0
  morgan: ^1.10.0
  next: 15.4.7
  payload: 3.55.0
  playwright: 1.54.1
  playwright-core: 1.54.1
  prettier: ^3.4.2
  react: 19.1.0
  react-dom: 19.1.0
  react-router: ^7.7.1
  sharp: 0.34.2
  tailwindcss: ^4.1.4
  typescript: 5.7.3
  vite: ^6.3.3
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.3
  winston: ^3.11.0
  '@types/winston': ^2.4.4
  express-rate-limit: ^7.1.5
  helmet: ^7.1.0
  cors: ^2.8.5
  express-validator: ^7.0.1
  csurf: ^1.11.0
  '@types/csurf': ^1.11.5
  zod: ^3.22.4

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
