name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'needs-triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here...

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Select your environment
      options:
        - Development
        - Production
        - Staging
        - Local
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: e.g., macOS 14.0, Windows 11, Ubuntu 24.8.0
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: e.g., 18.17.0
    validations:
      required: true

  - type: input
    id: pnpm-version
    attributes:
      label: pnpm Version
      description: What version of pnpm are you using?
      placeholder: e.g., 8.10.0
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser (if applicable)
      description: What browser are you using?
      placeholder: e.g., Chrome 119, Firefox 119, Safari 17
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: If applicable, paste any error logs or console output.
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the information requested above
          required: true
        - label: I am using the latest version of the project
          required: true
